"use client"; // Required for context providers in App Router
import { SessionProvider } from "next-auth/react";
import { Inter, Roboto_Mono } from "next/font/google";

import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import AppWrapper from "@/app/components/app-wrapper";

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${robotoMono.variable}`}>
        <SessionProvider>
          <AppWrapper children={children} />
        </SessionProvider>
      </body>
    </html>
  );
}
