import mongoose from "mongoose";

const UserSchema = new mongoose.Schema(
  {
    name: { type: String },
    given_name: { type: String },
    family_name: { type: String },
    email: { type: String, unique: true, required: true },
    password: { type: String },
    age: { type: Number },
    currentWeightKG: { type: Number },
    currentWeightLBS: { type: Number },
    startingWeightKG: { type: Number },
    startingWeightLBS: { type: Number },
    goalWeightKG: { type: Number },
    goalWeightLBS: { type: Number },
    heightImperial: { type: [Number] },
    heightMetric: { type: Number },
    image: { type: String },
    profilePicture: { type: String },
    preference: { type: String },
    gender: { type: String },
    bmiKG: { type: Number },
    bmiLBS: { type: Number },
    activityLevel: { type: Number },
    weightLossPerWeekKG: { type: Number },
    weightLossPerWeekLBS: { type: Number },
    dailyCalorieGoal: { type: Number },

    days: [
      {
        date: { type: String },
        weightKG: { type: Number },
        weightLBS: { type: Number },
        goalWeightKG: { type: Number },
        goalWeightLBS: { type: Number },
        breakfast: {
          foodItems: Array,
          calories: { type: Number },
          carbohydrates: { type: Number },
          protein: { type: Number },
          fat: { type: Number },
          proteinPercentage: { type: Number },
          fatPercentage: { type: Number },
          carbohydratePercentage: { type: Number },
        },
        lunch: {
          foodItems: Array,
          calories: { type: Number },
          carbohydrates: { type: Number },
          protein: { type: Number },
          fat: { type: Number },
          proteinPercentage: { type: Number },
          fatPercentage: { type: Number },
          carbohydratePercentage: { type: Number },
        },
        dinner: {
          foodItems: Array,
          calories: { type: Number },
          carbohydrates: { type: Number },
          protein: { type: Number },
          fat: { type: Number },
          proteinPercentage: { type: Number },
          fatPercentage: { type: Number },
          carbohydratePercentage: { type: Number },
        },
        snacks: {
          foodItems: Array,
          calories: { type: Number },
          carbohydrates: { type: Number },
          protein: { type: Number },
          fat: { type: Number },
          proteinPercentage: { type: Number },
          fatPercentage: { type: Number },
          carbohydratePercentage: { type: Number },
        },
        totals: {
          calories: { type: Number },
          carbohydrates: { type: Number },
          protein: { type: Number },
          fat: { type: Number },
          proteinPercentage: { type: Number },
          fatPercentage: { type: Number },
          carbohydratePercentage: { type: Number },
        },
      },
    ],
  },
  { timestamps: true }
);

export default mongoose.models.User || mongoose.model("User", UserSchema);
